# Generated by Django 5.0.7 on 2024-07-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('number_nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagprint.nfe')),
            ],
        ),
    ]
