# Generated by Django 5.0.7 on 2024-07-10 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagprint', '0002_nfe_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number_nfe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagprint.nfe', to_field='number'),
        ),
    ]
