# Generated by Django 5.0.7 on 2024-07-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagprint', '0003_alter_tag_number_nfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
